version: 2.1

executors:
  golang:
    docker:
      - image: cimg/go:1.24

jobs:
  release:
    executor: golang
    steps:
      - checkout
      - run:
          name: Tag and push
          command: |
            tag="v0.0.<< pipeline.number >>"
            git tag "$tag"
            git push https://$GITHUB_TOKEN@github.com/tibber/prestop-signal.git "$tag"
          environment:
            GITHUB_TOKEN: $GITHUB_AUTH_TOKEN
      - run:
          name: Install GoReleaser
          command: |
            curl -sSfL https://goreleaser.com/static/run | bash -s -- release --clean
          environment:
            GITHUB_TOKEN: $GITHUB_AUTH_TOKEN

workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              only: main
          context:
            - GITHUB
