version: 2.1

orbs:
  gh: circleci/github-cli@2.6

executors:
  golang:
    docker:
      - image: cimg/go:1.24

jobs:
  release:
    executor: golang
    steps:
      - checkout
      - gh/setup
      - run:
          name: Create GitHub release
          command: |
            gh release create "v0.0.<< pipeline.number >>"
      - run:
          name: Install and run GoReleaser
          command: |
            curl -sSfL https://goreleaser.com/static/run | bash -s -- release --clean

workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              only:
                - main
          context:
            - GITHUB
